# Generated by Django 4.2.4 on 2023-09-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_comment_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
